project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "ml-25m"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



